---
- name: Stop container for PVE
  community.general.proxmox:
    hostname: "{{ item['hostname'] if item.get('hostname') else ( global['hostname'] if global['hostname'] else omit ) }}"
    node: "{{ item['node'] if item.get('node') else ( global['node'] if global['node'] else omit ) }}"
    api_user: "{{ item['api_user'] if item.get('api_user') else ( global['api_user'] if global['api_user'] else omit ) }}"
    api_password: "{{ item['api_password'] if item.get('api_password') else ( global['api_password'] if global['api_password'] else omit ) }}"
    api_host: "{{ item['api_host'] if item.get('api_host') else ( global['api_host'] if global['api_host'] else omit ) }}"
    state: stopped
  delegate_to: localhost
  with_items: "{{ vm_list | default([]) }}"
  tags:
  - stop

- name: Delete container for PVE
  community.general.proxmox:
    hostname: "{{ item['hostname'] if item.get('hostname') else ( global['hostname'] if global['hostname'] else omit ) }}"
    node: "{{ item['node'] if item.get('node') else ( global['node'] if global['node'] else omit ) }}"
    api_user: "{{ item['api_user'] if item.get('api_user') else ( global['api_user'] if global['api_user'] else omit ) }}"
    api_password: "{{ item['api_password'] if item.get('api_password') else ( global['api_password'] if global['api_password'] else omit ) }}"
    api_host: "{{ item['api_host'] if item.get('api_host') else ( global['api_host'] if global['api_host'] else omit ) }}"
    state: absent
  delegate_to: localhost
  with_items: "{{ vm_list | default([]) }}"
  tags:
  - delete